/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bloodbank;
import javax.swing.*;
import com.mysql.cj.jdbc.Driver;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Getch
 */
public class DonerPage extends javax.swing.JFrame {

    /**
     * Creates new form DonerPage
     */
    public DonerPage() {
        initComponents();
         long millis=System.currentTimeMillis();
         java.sql.Date date=new java.sql.Date(millis);
         DateText.setText(date.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GenderGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        DonerText = new javax.swing.JTextField();
        BloogGroupCombo = new javax.swing.JComboBox<>();
        Malechack = new javax.swing.JCheckBox();
        FimaleChack = new javax.swing.JCheckBox();
        AgeText = new javax.swing.JTextField();
        CityText = new javax.swing.JTextField();
        MobileText = new javax.swing.JTextField();
        DateText = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        HomeBtn = new javax.swing.JButton();
        SubmitBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 255));
        setMinimumSize(new java.awt.Dimension(890, 515));
        addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                formPropertyChange(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 102, 102));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Doner Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(43, 130, 78, 16);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Blood Group");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(43, 201, 77, 16);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Sex");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(43, 260, 23, 16);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("Age");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(42, 333, 26, 16);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("Mobile");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(526, 201, 41, 16);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setText("City");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(526, 130, 30, 16);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setText("Date");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(526, 260, 31, 16);
        getContentPane().add(DonerText);
        DonerText.setBounds(170, 120, 207, 24);

        BloogGroupCombo.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        BloogGroupCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "AB", "O" }));
        getContentPane().add(BloogGroupCombo);
        BloogGroupCombo.setBounds(170, 190, 80, 29);

        GenderGroup.add(Malechack);
        Malechack.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Malechack.setText("Male");
        getContentPane().add(Malechack);
        Malechack.setBounds(177, 256, 55, 25);

        GenderGroup.add(FimaleChack);
        FimaleChack.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        FimaleChack.setText("Female");
        getContentPane().add(FimaleChack);
        FimaleChack.setBounds(268, 256, 69, 25);
        getContentPane().add(AgeText);
        AgeText.setBounds(120, 330, 83, 20);

        CityText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CityTextActionPerformed(evt);
            }
        });
        getContentPane().add(CityText);
        CityText.setBounds(618, 125, 209, 24);

        MobileText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MobileTextActionPerformed(evt);
            }
        });
        getContentPane().add(MobileText);
        MobileText.setBounds(618, 194, 209, 29);

        DateText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateTextActionPerformed(evt);
            }
        });
        getContentPane().add(DateText);
        DateText.setBounds(618, 256, 209, 23);

        jLabel8.setBackground(new java.awt.Color(235, 29, 54));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("                             Donor Form");
        jLabel8.setOpaque(true);
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 879, 47);

        HomeBtn.setBackground(new java.awt.Color(235, 29, 54));
        HomeBtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        HomeBtn.setForeground(new java.awt.Color(245, 237, 220));
        HomeBtn.setText("Back");
        HomeBtn.setBorderPainted(false);
        HomeBtn.setOpaque(false);
        HomeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeBtnActionPerformed(evt);
            }
        });
        getContentPane().add(HomeBtn);
        HomeBtn.setBounds(387, 420, 97, 31);

        SubmitBtn.setBackground(new java.awt.Color(235, 29, 54));
        SubmitBtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        SubmitBtn.setForeground(new java.awt.Color(245, 237, 220));
        SubmitBtn.setText("Submit");
        SubmitBtn.setOpaque(false);
        SubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitBtnActionPerformed(evt);
            }
        });
        getContentPane().add(SubmitBtn);
        SubmitBtn.setBounds(630, 420, 94, 31);

        jLabel9.setBackground(new java.awt.Color(207, 210, 207));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setOpaque(true);
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 880, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DateTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateTextActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_DateTextActionPerformed

    private void SubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitBtnActionPerformed
        // TODO add your handling code here:
        
        
       String name=DonerText.getText();
       String BloodGroup=BloogGroupCombo.getSelectedItem().toString();
       String sex=Malechack.isSelected() ? Malechack.getText():FimaleChack.getText();
       String Age=AgeText.getText();
       String City=CityText.getText();
       String Mobile=MobileText.getText();
       String date=DateText.getText();
        try {
     
           String mysql="INSERT INTO doners  VALUES(?, ? ,? ,?,?,?,?,?)";
           Class.forName("com.mysql.cj.jdbc.Driver");
          Connection connection= DriverManager.getConnection("jdbc:mysql://localhost/bloodbank","root","root");
           PreparedStatement ps=connection.prepareStatement(mysql);
                ps.setString(1,null);
                ps.setString(2,name);
                ps.setString(3,BloodGroup);
                ps.setString(4,sex);
                ps.setString(5,Age);
                ps.setString(6,City);
                ps.setString(7,Mobile);
                ps.setString(8,date);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this,"Form is Saved Successfully ","Empty",JOptionPane.PLAIN_MESSAGE);

                ps.close();     
                    
                    } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(DonerPage.class.getName()).log(Level.SEVERE, null, ex);
        }
                 
      
    }//GEN-LAST:event_SubmitBtnActionPerformed

    private void MobileTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MobileTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MobileTextActionPerformed

    private void CityTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CityTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CityTextActionPerformed

    private void HomeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeBtnActionPerformed
        // TODO add your handling code here:
           dispose();
                home Home=new home();
                Home.setVisible(true);
                Home.setBounds(220,50,400,300);
    }//GEN-LAST:event_HomeBtnActionPerformed

    private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DonerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DonerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DonerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DonerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DonerPage().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AgeText;
    private javax.swing.JComboBox<String> BloogGroupCombo;
    private javax.swing.JTextField CityText;
    private javax.swing.JTextField DateText;
    private javax.swing.JTextField DonerText;
    private javax.swing.JCheckBox FimaleChack;
    private javax.swing.ButtonGroup GenderGroup;
    private javax.swing.JButton HomeBtn;
    private javax.swing.JCheckBox Malechack;
    private javax.swing.JTextField MobileText;
    private javax.swing.JButton SubmitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
