/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bloodbank;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Getch
 */
public class SearchDoner extends javax.swing.JFrame {

    /**
     * Creates new form SearchDoner
     */
    
    public SearchDoner() {
        initComponents();
        
       
        
    }
void Searching(String Quary){

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection cn=DriverManager.getConnection("jdbc:mysql://localhost/bloodbank","root","root");
            DefaultTableModel table =(DefaultTableModel)ResaltTable.getModel();
            PreparedStatement smt=cn.prepareStatement(Quary);
            ResultSet rs=smt.executeQuery();
       while(rs.next()){
    
                    String a1=rs.getString(1);
                    String a2=rs.getString(2);
                    String a3=rs.getString(3);
                    String a4=rs.getString(4);
                    String a5=rs.getString(5);
                    String a6=rs.getString(6);
                    String a7=rs.getString(7);
                    String a8=rs.getString(8);

Object pc[]={a1,a2,a3,a4,a5,a6,a7,a8};
table.addRow(pc);

}  
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(SearchDoner.class.getName()).log(Level.SEVERE, null, ex);
        }


}

    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SeachGroupBtn = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        ResaltTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NameCheckBox = new javax.swing.JCheckBox();
        BGroupCheckBox = new javax.swing.JCheckBox();
        SrearchLable = new javax.swing.JLabel();
        SearchedText = new javax.swing.JTextField();
        SeachBtn = new javax.swing.JButton();
        HomeBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setFocusCycleRoot(false);
        setMinimumSize(new java.awt.Dimension(900, 460));

        jScrollPane1.setToolTipText("");

        ResaltTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Blood Group", "Sex", "Age", "City", "Mobile", "Date"
            }
        ));
        jScrollPane1.setViewportView(ResaltTable);

        jLabel1.setBackground(new java.awt.Color(235, 29, 54));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("                            Search Doner");
        jLabel1.setOpaque(true);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Search By");
        jLabel2.setToolTipText("");

        SeachGroupBtn.add(NameCheckBox);
        NameCheckBox.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        NameCheckBox.setText("Name");
        NameCheckBox.setToolTipText("");
        NameCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameCheckBoxActionPerformed(evt);
            }
        });

        SeachGroupBtn.add(BGroupCheckBox);
        BGroupCheckBox.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        BGroupCheckBox.setText("Blood Group");
        BGroupCheckBox.setToolTipText("");
        BGroupCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BGroupCheckBoxActionPerformed(evt);
            }
        });

        SrearchLable.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        SrearchLable.setText("Select Search option");
        SrearchLable.setToolTipText("");

        SeachBtn.setBackground(new java.awt.Color(235, 29, 54));
        SeachBtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        SeachBtn.setForeground(new java.awt.Color(255, 255, 255));
        SeachBtn.setText("Search");
        SeachBtn.setToolTipText("");
        SeachBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeachBtnActionPerformed(evt);
            }
        });

        HomeBtn.setBackground(new java.awt.Color(235, 29, 54));
        HomeBtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        HomeBtn.setForeground(new java.awt.Color(255, 255, 255));
        HomeBtn.setText("Home");
        HomeBtn.setToolTipText("");
        HomeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(43, 43, 43)
                        .addComponent(NameCheckBox)
                        .addGap(31, 31, 31)
                        .addComponent(BGroupCheckBox)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SrearchLable)
                        .addGap(18, 18, 18)
                        .addComponent(SearchedText, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SeachBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                        .addComponent(HomeBtn)
                        .addGap(83, 83, 83))))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(NameCheckBox)
                    .addComponent(BGroupCheckBox))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(HomeBtn)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SearchedText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SeachBtn)
                            .addComponent(SrearchLable))
                        .addGap(39, 39, 39))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BGroupCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BGroupCheckBoxActionPerformed
        // TODO add your handling code here:
       SrearchLable.setText("Enter Blood Group");
      
    }//GEN-LAST:event_BGroupCheckBoxActionPerformed

    private void NameCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameCheckBoxActionPerformed
        // TODO add your handling code here:
        SrearchLable.setText("Enter Doner Name ");
    }//GEN-LAST:event_NameCheckBoxActionPerformed

    private void SeachBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeachBtnActionPerformed
        // TODO add your handling code here:
        String SreachInput=SearchedText.getText();
        String mysql = null;
        boolean Selected=false;
        if(NameCheckBox.isSelected()){
             mysql="select * from doners where name='"+SreachInput+"'";  
            Selected=true;
        
        }
        else if(BGroupCheckBox.isSelected()){
            mysql="select * from doners where bloodGroup='"+SreachInput+"'"; 
           Selected=true;
        }
        else{
          JOptionPane.showMessageDialog(this,"Please select your search option !! ","Empty",JOptionPane.PLAIN_MESSAGE);

        }
      if(Selected){
          Searching(mysql);
      }
       
    }//GEN-LAST:event_SeachBtnActionPerformed

    private void HomeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeBtnActionPerformed
        // TODO add your handling code here:
           dispose();
          home Home=new home();
                Home.setVisible(true);
                Home.setBounds(220,50,400,300);
    }//GEN-LAST:event_HomeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchDoner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchDoner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchDoner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchDoner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new SearchDoner().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox BGroupCheckBox;
    private javax.swing.JButton HomeBtn;
    private javax.swing.JCheckBox NameCheckBox;
    private javax.swing.JTable ResaltTable;
    private javax.swing.JButton SeachBtn;
    private javax.swing.ButtonGroup SeachGroupBtn;
    private javax.swing.JTextField SearchedText;
    private javax.swing.JLabel SrearchLable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
